#!/bin/sh

echo "compiling with Check susbsytem"
echo

./run-dev0 <<DATA
DevCompiler.CompileSubs Lin System Std Cons Text Form Dev Comm Fig Obx Check
Kernel.Quit(0)
DATA

echo
echo "linking gui"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe Linux blackbox := Kernel$+ Utf LinKernel Files LinEnv LinFiles LinGui StdLoader LinLoader
Kernel.Quit(0)
DATA

echo
echo "linking interp"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe Linux blackboxInterp := Kernel$+ Utf LinKernel Files LinEnv LinFiles StdLoader LinIntLoader
Kernel.Quit(0)
DATA
