#!/bin/sh

echo "compiling"
echo

./run-dev0 <<DATA
DevCompiler.CompileSubs @Obsd Obsd System Std Cons Text Form Dev Comm Fig Obx Sql Paket
DATA

echo
echo "linking GUI"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe OpenBSD blackboxOpenBSD := Kernel$+ Utf ObsdKernel Files ObsdEnv ObsdFiles ObsdGui StdLoader ObsdLoader
DATA

echo
echo "linking GUI (DevBootLinker)"
echo

./run-dev0 <<DATA
DevBootLinker.SetLoaderName("Dev/Rsrc/exeOpenBSD.img")
DevBootLinker.Link blackboxOpenBSD.run := Kernel+$ Utf ObsdKernel Files ObsdEnv ObsdFiles ObsdGui StdLoader ObsdLoader
DATA
chmod +x blackboxOpenBSD.run


echo
echo "linking interpreter"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe OpenBSD blackboxInterpOpenBSD := Kernel$+ Utf ObsdKernel Files ObsdEnv ObsdFiles StdLoader ObsdIntLoader
DATA

echo
echo "linking interpreter (DevBootLinker)"
echo

./run-dev0 <<DATA
DevBootLinker.SetLoaderName("Dev/Rsrc/exeOpenBSD.img")
DevBootLinker.Link blackboxInterpOpenBSD.run := Kernel+$ Utf ObsdKernel Files ObsdEnv ObsdFiles StdLoader ObsdIntLoader
DATA
chmod +x blackboxInterpOpenBSD.run
