#!/bin/sh

echo "\ncompiling with Check susbsytem\n"

./run-dev0 <<DATA
DevCompiler.CompileSubs Lin System Std Cons Text Form Dev Comm Obx Check
Kernel.Quit(0)
DATA

echo "\nlinking gui\n"

./run-dev0 <<DATA
DevLinker1.LinkElfExe Linux blackbox := Kernel$+ Utf LinKernel Files LinEnv LinFiles LinGui StdLoader LinLoader
Kernel.Quit(0)
DATA

echo "\nlinking interp\n"

./run-dev0 <<DATA
DevLinker1.LinkElfExe Linux blackboxInterp := Kernel$+ Utf LinKernel Files LinEnv LinFiles StdLoader LinIntLoader
Kernel.Quit(0)
DATA

