#!/bin/sh

echo "compiling"
echo

./run-dev0 <<DATA
DevCompiler.CompileSubs @Fbsd Fbsd System Std Cons Text Form Dev Comm Fig Obx Raster
DATA

echo
echo "linking GUI"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe FreeBSD blackbox := Kernel$+ Utf FbsdKernel Files FbsdEnv FbsdFiles FbsdGui StdLoader FbsdLoader
DATA

echo
echo "linking interpreter"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe FreeBSD blackboxInterp := Kernel$+ Utf FbsdKernel Files FbsdEnv FbsdFiles StdLoader FbsdIntLoader
DATA
