#!/bin/sh

echo "compiling"

./run-dev0 <<DATA
DevCompiler.CompileSubs Com Comm Ctl Dev Form Ole Sql Std System Text Win Cons Mdi Obx
Kernel.Quit(0)
DATA

echo "\nlinking gui\n"

./run-dev0 <<DATA
DevLinker.Link BlackBox.exe := Kernel$+ Utf WinKernel Files WinEnv WinFiles WinGui StdLoader WinLoader 1 BlackBox.res 1 Applogo.ico 2 Doclogo.ico 3 SFLogo.ico 4 CFLogo.ico 5 DtyLogo.ico 6 folderimg.ico 7 openimg.ico 8 leafimg.ico 1 Move.cur 2 Copy.cur 3 Link.cur 4 Pick.cur 5 Stop.cur 6 Hand.cur 7 Table.cur
Kernel.Quit(0)
DATA

echo "\nlinking gui mdi\n"

./run-dev0 <<DATA
DevLinker.Link BlackBoxMDI.exe := Kernel$+ Utf WinKernel Files WinEnv WinFiles WinGui StdLoader MdiLoader 1 BlackBox.res 1 Applogo.ico 2 Doclogo.ico 3 SFLogo.ico 4 CFLogo.ico 5 DtyLogo.ico 6 folderimg.ico 7 openimg.ico 8 leafimg.ico 1 Move.cur 2 Copy.cur 3 Link.cur 4 Pick.cur 5 Stop.cur 6 Hand.cur 7 Table.cur
Kernel.Quit(0)
DATA

echo "\nlinking interp\n"

./run-dev0 <<DATA
DevLinker.Link BlackBoxInterp.exe := Kernel$+ Utf WinKernel Files WinEnv WinFiles StdLoader WinIntLoader
Kernel.Quit(0)
DATA
