#!/bin/sh

echo "compiling"
echo

./run-dev0 <<DATA
DevCompiler.CompileSubs @Fbsd Fbsd System Std Cons Text Form Dev Comm Fig Obx Sql Paket
DATA

echo
echo "linking GUI"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe FreeBSD blackboxFreeBSD := Kernel$+ Utf FbsdKernel Files FbsdEnv FbsdFiles FbsdGui StdLoader FbsdLoader
DATA

echo
echo "linking interpreter"
echo

./run-dev0 <<DATA
DevLinker1.LinkElfExe FreeBSD blackboxInterpFreeBSD := Kernel$+ Utf FbsdKernel Files FbsdEnv FbsdFiles StdLoader FbsdIntLoader
DATA
