#!/bin/sh

if [ $# -eq 1 ]; then
	outDir="${1}"
	if [ ! -e "${outDir}" ]; then
		mkdir "${outDir}"
		pax -r -w -L \
			-s ',.*/Xtras.*,,' \
			-s ',.*__Lin.*,,' -s ',.*__Fbsd.*,,' -s ',.*__Win.*,,' \
			Comm Cons Dev Docu Form Fig Obx Obsd Sql Std System Text Xhtml Paket blackbox blackboxInterp run-BlackBox run-BlackBoxInterp LICENSE.txt \
			"${outDir}"
	else
		echo "${outDir}: already exists"
		exit 2
	fi
else
	echo "usage: `basename $0` outputDirectory"
	exit 1
fi
