#!/bin/sh

# ulimit -s 32000
# ulimit -a

rn=`readlink -f "${0}"`
standardDir=`dirname "${rn}"`
useDir=`readlink -f .`
os=`uname -s`

if [ "$os" = "Linux" ]; then
    exe="dev0lin"
elif [ "$os" = "OpenBSD" ]; then
    exe="dev0obsd"
elif [ "$os" = "FreeBSD" ]; then
    exe="dev0fbsd"
else
    echo "unsupported OS"
fi

# export LD_DEBUG=all
exec env \
    BB_STANDART_DIR="${standardDir}" BB_USE_DIR="${useDir}" \
	BB_PACKED_NAME="${exe}" BB_PACKED_FIRST=  \
	"${standardDir}"/${exe} "${@}"
