#!/bin/sh

# ulimit -s 32000
# ulimit -a

rn=$(readlink -f "${0}")
standardDir=$(dirname "${rn}")
useDir=$(readlink -f .)

exeBase="dev0"

os=$(uname -s)
case "${os%%-*}" in
	"Linux")
		exe="${exeBase}Linux"
		;;
	"OpenBSD")
		exe="${exeBase}OpenBSD"
		;;
	"FreeBSD")
		exe="${exeBase}FreeBSD"
		;;
	"MSYS_NT" | "MINGW64_NT" | "MINGW32_NT")
		exe="${exeBase}"
		;;
	*)
		echo "unsupported OS"
		exit 1
esac

# export LD_DEBUG=all
exec env \
	BB_STANDART_DIR="${standardDir}" BB_USE_DIR="${useDir}" \
	BB_PACKED_NAME="${exe}" BB_PACKED_FIRST=  \
	"${standardDir}"/${exe} "${@}"
