#!/bin/sh

TARGET=`uname -s`
# TARGET=Linux

./switch-target ${TARGET} Interp
./build
./switch-target ${TARGET} GUI

./run-BlackBox <<DATA
DevCompiler.CompileThis FormModels FormViews FormControllers FormCmds FormGen

DevCompiler.CompileThis Gtk2GLib Gtk2GObject Gtk2Keysyms Gtk2Pango Gtk2Gdk Gtk2Gtk Gtk2Util

# HostRegistry required by DevBrowser
# HostTextConv must be recompiled, because it depend on HostFonts, and interp HostFonts has different fingerprint
DevCompiler.CompileThis HostRegistry HostUtf8 HostFonts HostTextConv HostPorts StdTables HostMechanisms HostCFrames HostWindows HostClipboard HostDialog StdTabViews HostTabFrames HostCmds HostMenus StdMenuTool

DevCompiler.CompileThis Config Init

###

DevCompiler.CompileThis DevAlienTool DevDebug DevDependencies DevHeapSpy DevInspector DevLinkChk DevMsgSpy DevRBrowser DevReferences DevSearch DevSubTool DevCmds DevBrowser

DevCompiler.CompileThis ObxActions ObxAddress0 ObxAddress1 ObxAddress2 ObxAscii ObxBlackBox ObxButtons ObxCalc ObxCaps ObxContIter ObxControlShifter ObxControls ObxConv ObxCount0 ObxCount1 ObxCubes ObxDb ObxDialog ObxFact ObxFileTree ObxFldCtrls ObxGraphs ObxHello1 ObxLabelLister ObxLines ObxLinks ObxMMerge ObxOmosi ObxOpen0 ObxOpen1 ObxOrders ObxParCmd ObxPatterns ObxRatcalc ObxSample ObxScroll ObxStores ObxTabViews ObxTabs ObxTickers ObxTwins ObxUnitConv ObxViews0 ObxViews1 ObxViews10 ObxViews11 ObxViews12 ObxViews13 ObxViews14 ObxViews2 ObxViews3 ObxViews4 ObxViews5 ObxViews6 ObxWrappers
DevCompiler.CompileThis ObxPhoneDB ObxPhoneUI ObxPhoneUI1 ObxLookup0 ObxLookup1 ObxPDBRep0 ObxPDBRep1 ObxPDBRep2 ObxPDBRep3 ObxPDBRep4

# TRAP:
#DevCompiler.CompileThis ObxCtrls
DATA
