#!/bin/sh

# ulimit -s 32000
# ulimit -a

rn=`readlink -f "${0}"`
pd=`dirname "${rn}"`
sd=`readlink -f .`

loader="loader"
lib="libBB.so"

# fix Ubuntu-specific problems:
unset UBUNTU_MENUPROXY
unset GTK_MODULES

# export LD_DEBUG=all
env \
	BB_PRIMARY_DIR="${pd}" BB_SECONDARY_DIR="${sd}" \
	BB_PACKED_NAME="${lib}" \
	"${pd}"/${loader} "${pd}"/${lib}
