#!/bin/sh

# fix Ubuntu-specific problems:
unset UBUNTU_MENUPROXY
unset GTK_MODULES
export LIBOVERLAY_SCROLLBAR=0
mv Code Code_
env \
  BB_PRIMARY_DIR="../../new" BB_SECONDARY_DIR="$PWD" \
../../new/blackbox
