#!/bin/sh

./run-dev0 <<DATA
ConsCompiler.Compile('Lin/Mod', 'Dl.txt')
ConsCompiler.Compile('Lin/Mod', 'Libc.txt')
ConsCompiler.Compile('Lin/Mod', 'LibW.txt')
ConsCompiler.Compile('Lin/Mod', 'Iconv.txt')
ConsCompiler.Compile('Lin/Mod', 'Termios.txt')
ConsCompiler.Compile('Lin/Mod', 'Ioctl.txt')
ConsCompiler.Compile('Lin/Mod', 'Net.txt')
ConsCompiler.Compile('Lin/Mod', 'Rt.txt')

DevCompiler.CompileSubs System Gtk2 Std Cons Host Text Form Dev Xhtml Comm Obx

### Dev2
DevCompiler.CompileThis Dev2LnkBase Dev2LnkLoad Dev2LnkWritePe Dev2LnkWriteElf Dev2LnkWriteElfStatic Dev2Linker Dev2Linker1
DevCompiler.CompileThis Dev2LnkChmod

Dev2Linker1.LinkElfExe `uname -s` blackbox := Kernel$+ Files HostFiles HostGnome StdLoader

DATA
