#!/bin/sh

# fix Ubuntu-specific problems:
unset UBUNTU_MENUPROXY
unset GTK_MODULES
export LIBOVERLAY_SCROLLBAR=0
env \
  BB_PRIMARY_DIR="../../BlackBox" BB_SECONDARY_DIR="$PWD" \
  ../../BlackBox/blackbox
