#!/bin/sh

./run-dev0 <<DATA
DevCompiler.CompileSubs Lin System Std Host Cons Text Form Dev Xhtml Comm Obx

### Dev2
DevCompiler.CompileThis Dev2LnkBase Dev2LnkLoad Dev2LnkWritePe Dev2LnkWriteElf Dev2LnkWriteElfStatic Dev2Linker Dev2Linker1
DevCompiler.CompileThis Dev2LnkChmod

Dev2Linker1.LinkElfExe `uname -s` blackbox := Kernel$+ Files HostFiles StdLoader

DATA
