#!/bin/sh

echo "cleaning"

./clean

echo "compiling"

./run-dev0 <<DATA
DevCompiler.CompileSubs Lin System Std Cons Var Text Form Dev Dev2 Tyler
Kernel.Quit(0)
DATA

echo "linking"

./run-dev0 <<DATA
Dev2Linker1.LinkElfExe `uname -s` blackbox := Unicode Kernel$+ Files Utf LinEnv LinFiles LinGui StdLoader LinLoader
Kernel.Quit(0)
DATA
