#!/bin/sh

echo "cleaning"

./clean

echo "compiling"

./run-dev0 <<DATA
DevCompiler.CompileSubs Com Comm Ctl Dev Form Ole Sql Std System Text Win Cons Winint
Kernel.Quit(0)
DATA

echo "linking"

./run-dev0 <<DATA
DevLinker.Link BlackBox.exe := Unicode Kernel$+ Files Utf WinKernel WinEnv WinFiles StdLoader WinintLoader
Kernel.Quit(0)
DATA
