#!/bin/sh

# ulimit -s 32000
# ulimit -a

rn=`readlink -f "${0}"`
pd=`dirname "${rn}"`
sd=`readlink -f .`

exe="blackbox"

# fix Ubuntu-specific problems:
unset UBUNTU_MENUPROXY
unset GTK_MODULES
export LIBOVERLAY_SCROLLBAR=0

# export LD_DEBUG=all
exec env \
	BB_PRIMARY_DIR="${pd}" BB_SECONDARY_DIR="${sd}" \
	BB_PACKED_NAME="${exe}" \
	"${pd}"/${exe}
