#!/bin/sh

# ulimit -s 32000
# ulimit -a

rn=`readlink -f "${0}"`
standardDir=`dirname "${rn}"`
useDir=`readlink -f .`

exe="dev0lin"

# export LD_DEBUG=all
exec env \
    BB_STANDART_DIR="${standardDir}" BB_USE_DIR="${useDir}" \
	BB_PACKED_NAME="${exe}" BB_PACKED_FIRST=  \
	"${standardDir}"/${exe} "${@}"
