name: Build and Package .deb

on:
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y libgtk2.0-0:i386 gtk2-engines:i386 gtk2-engines-murrine:i386 libcanberra-gtk-module:i386
          sudo apt-get install -y pax
          sudo apt-get install -y md5deep lintian

      - name: Build the application
        run: ./build-linux

      - name: Build the .deb package
        run: ./makePackage
        working-directory: packaging/Deb

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: bbcb-deb
          path: packaging/Deb/*.deb
